name: CI Testing

# CINTENT >> MANUAL_TRIGGER
# on:
#   push:
#     branches: [ develop ]
#     tags:
#       - '[0-9]+\.[0-9]+\.[0-9]+'
#       - '[0-9]+\.[0-9]+\.[0-9]+-*'
#   pull_request:
#     branches: [ main ]
on: [repository_dispatch, workflow_dispatch]

jobs:
  run_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # CINTENT >> REMOVE_MATRIX
        # python: [ '3.10', '3.11' , '3.12' ]
        python: [ '3.12' ]

        # CINTENT >> UNSUPPORTED_OS
        # os: [ macos-latest, ubuntu-latest ]
        os: [ ubuntu-latest ]

        # CINTENT >> REMOVE_MATRIX
        # include:
        #   - python: '3.10'
        #     torch: '1.12'
        #   - python: '3.11'
        #     torch: '2.1'
        #   - python: '3.12'
        #     torch: '2.5'
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3638849e94bdb037f0a405375686a8550e6df904
        with:
          nonblocking: true

      - name: Install cryoDRGN with pytest dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest-xdist
          python3 -m pip install .
          # python3 -m pip uninstall -y torch
          # python3 -m pip cache purge
          # python3 -m pip install torch==${{ matrix.torch }}

      - name: Pytest
        run: |
          pytest -v -n2 --dist=loadscope --show-capture=stderr

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
